package:
    name: curio
    version: {{ GIT_DESCRIBE_TAG  }}+git.{{ GIT_DESCRIBE_NUMBER }}

source:
    git_url: https://github.com/dabeaz/curio
    git_rev: master

requirements:
    build:
        - setuptools
        - python
    run:
        - python

about:
    home: https://curio.readthedocs.io/en/latest/
    licence_file: LICENSE
