## Load image with software requirements for libnnpdf
image: zaharid/conda-centos

stages:
    - build-deploy


#Set to "true" to generate builds for non-default branches
variables:
    UPLOAD_NON_MASTER: "true"
    CONDAPATH: "/root/miniconda3/"
    OUTPUT_ARCH: "linux-64"
    OUTPUT_CHANNEL: "conda-pkgs"

## Run the configure and make tests
job1:
    variables:
        CONDA_PY: "35"
    stage: build-deploy
    script: ".ciscripts/build-all.sh"


job2:
    variables:
        CONDA_PY: "36"
    stage: build-deploy
    script: ".ciscripts/build-all.sh"
