# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os:
  - osx
  - linux

osx_image: xcode6.4

env:
  global:
    - CONDAPATH="/Users/travis/miniconda3"
    - OUTPUT_ARCH=osx-64
    - OUTPUT_CHANNEL=conda

  matrix:
    - CONDA_PY=37
    - CONDA_PY=38


before_install:
    # Remove homebrew.
    - |
      if [[ "$TRAVIS_OS_NAME" == "osx" ]];
      then
      brew remove --force --ignore-dependencies $(brew list)
      brew cleanup -s
      rm -rf $(brew --cache)
      elif [[ "$TRAVIS_OS_NAME" == "linux" ]];
      then
      docker pull zaharid/conda-bld
      docker run -itd --name build zaharid/conda-bld
      docker cp ../conda-recipes build:/
      fi

install:
    - |

      if [[ "$TRAVIS_OS_NAME" == "osx" ]];
      then
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --append channels conda-forge
      conda config --prepend channels https://packages.nnpdf.science/conda
      conda config --set show_channel_urls true
      conda install --yes conda-build
      fi

script:
  - |

    if [[ "$TRAVIS_OS_NAME" == "osx" ]];
    then
    ./.ciscripts/build-all.sh
    elif [[ "$TRAVIS_OS_NAME" == "linux" ]];
    then
    docker exec  \
        -e TRAVIS_OS_NAME\
        -e CONDA_PY\
        -e NNPDF_SSH_KEY\
        -e CI_BUILD_REF_NAME\
        -e TRAVIS_BRANCH\
        -e OUTPUT_CHANNEL\
        -e CONDAPATH=/root/miniconda3/\
        -e OUTPUT_ARCH=linux-64\
        -e BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}\
        build bash -c "cd /conda-recipes; .ciscripts/build-all.sh"
    fi

