package:
  name: yaml-cpp
  version: 0.5.3

source:
  git_url: https://github.com/jbeder/yaml-cpp/
  git_rev: release-0.5.3

build:
  number: 3
  binary_relocation: true

requirements:
  build:
    - gcc >5
    - cmake
    - boost
  run:
    - boost
    - libgcc >5

about:
  home: https://code.google.com/p/yaml-cpp/
  license: MIT
  summary: A YAML parser and emitter in C++
