package:
  name: yaml-cpp
  version: 0.6.0

source:
    url: https://github.com/jbeder/yaml-cpp/archive/yaml-cpp-0.6.0.tar.gz
    fn:  yaml-cpp-0.6.0.tar.gz
    md5: 8adc0ae6c2698a61ab086606cc7cf562

build:
  number: 4
  binary_relocation: true

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake

about:
  home: https://code.google.com/p/yaml-cpp/
  license: MIT
  summary: A YAML parser and emitter in C++
