package:
  name: yaml-cpp
  version: 0.5.3

source:
    url: https://github.com/jbeder/yaml-cpp/archive/yaml-cpp-0.5.3.tar.gz
    fn:  yaml-cpp-0.5.3.tar.gz

build:
  number: 3
  binary_relocation: true

requirements:
  build:
    - toolchain # [osx]
    - cmake
  host:
    - boost
  run:
    - boost

about:
  home: https://code.google.com/p/yaml-cpp/
  license: MIT
  summary: A YAML parser and emitter in C++
