{% set version = "6.4.0" %}
{% set filename = "LHAPDF-" + version + ".tar.gz" %}
{% set checksum = "64687d7f7e5f6e0ac03408d2007bfe31" %}

package:
    name: lhapdf
    version: {{ version }}

source:
    url: http://www.hepforge.org/archive/lhapdf/{{ filename }}
    md5: {{ checksum }}
    fn:  {{ filename }}

requirements:
    build:
        - {{compiler('cxx')}}
    host:
        - python
        - cython
    run:
        - python

build:
    number: 3
    detect_binary_files_with_prefix: True

test:
    commands:
        - lhapdf-config
        - python -c "import lhapdf"

about:
    home: https://lhapdf.hepforge.org/
    license: UNKNOWN
