package:
    name: lhapdf
    version: "6.2.1"

source:
    url: http://www.hepforge.org/archive/lhapdf/LHAPDF-6.2.1.tar.gz
    md5: 9e05567d538fdb4862d4781cd076d7db
    fn: LHAPDF-6.2.1.tar.gz

requirements:
    host:
        - python
        - cython
    run:
        - python

build:
    number: 0
    detect_binary_files_with_prefix: True

test:
    commands:
        - lhapdf-config
        - python -c "import lhapdf"

about:
    home: https://lhapdf.hepforge.org/
    license: UNKNOWN
