package:
    name: apfel
    version: "2.7.1.{{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}"

source:
    git_url: https://github.com/scarrazza/apfel
    git_rev: master
requirements:
    build: 
        - toolchain # [osx]
        - python >3.4
        - gcc # [linux]
        - libgcc # [linux]
        - lhapdf
    run:
        - libgcc # [linux]
        - lhapdf
        - python >3.4

build:
    number: 5
    detect_binary_files_with_prefix: True

test:
    commands:
        - apfel-config --checkapfel

about:
    home: https://apfel.hepforge.org/
    license: gpl
