package:
    name: apfel
    version: "{{GIT_DESCRIBE_TAG}}.{{ GIT_DESCRIBE_NUMBER }}"

source:
    git_url: https://github.com/scarrazza/apfel
    git_rev: master
requirements:
    build:
        - {{compiler('cxx')}}
        - {{compiler('fortran')}}
    host:
        - python
        - lhapdf
    run:
        - lhapdf
        - python

build:
    number: 7
    detect_binary_files_with_prefix: True

test:
    commands:
        - apfel-config --checkapfel

about:
    home: https://apfel.hepforge.org/
    license: gpl
