package:
    name: apfel
    version: "2.7.1.maaster"

source:
    git_url: https://github.com/scarrazza/apfel
    git_rev: master
requirements:
    build: 
        - python >3.4
        - gcc
        - libgcc
        - lhapdf
    run:
        - libgcc
        - lhapdf
        - python >3.4

build:
    number: 2
    detect_binary_files_with_prefix: True

test:
    commands:
        - apfel-config --checkapfel

about:
    home: https://apfel.hepforge.org/
    license: gpl
