name: ARM64 build

on: [push]

jobs:
    build:

        runs-on: ${{matrix.os}}

        strategy:
            matrix:
                os: [macOS-latest]
                python_version: ["3.8"]
        steps:
          - name: Install SSH key
            uses: shimataro/ssh-key-action@v2
            with:
                key: ${{ secrets.SSH_KEY }}
                known_hosts: ${{ secrets.KNOWN_HOSTS }}

          - uses: actions/checkout@v2

          - uses: conda-incubator/setup-miniconda@v2
            with:
              auto-update-conda: true
              python-version: ${{matrix.python_version}}

          - name: Get Mac OS SDK
            run: |
                curl -L -O https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX11.0.sdk.tar.xz;
                sudo tar xfz MacOSX11.0.sdk.tar.xz -C /opt/;
          - name: Do Build
            shell: bash -l {0}
            run: |
                conda install conda-build --yes
                conda build lhapdf -c conda-forge -m cross-compile.yml
                conda build apfel -c conda-forge -m cross-compile.yml --use-local

          - name: Upload
            shell: bash -l {0}
            run: |
                scp ${CONDA_PREFIX}/conda-bld/osx-arm64/*.tar.bz2 dummy@packages.nnpdf.science:~/packages/conda/osx-arm64

