name: Build

on: [push]

jobs:
    build:

        runs-on: ${{matrix.os}}

        strategy:
            matrix:
                os: [ubuntu-latest, macOS-latest]
                python_version: ["3.12"]
        steps:
          - name: Install SSH key
            uses: shimataro/ssh-key-action@v2
            with:
                key: ${{ secrets.SSH_KEY }}
                known_hosts: ${{ secrets.KNOWN_HOSTS }}

          - uses: actions/checkout@v2

          - uses: conda-incubator/setup-miniconda@v2
            with:
              auto-update-conda: true
              python-version: ${{matrix.python_version}}
              channels: conda-forge

          - name: Get Mac OS SDK
            if: runner.os == 'macOS'
            run: |
                curl -L -O https://data.nnpdf.science/MacOSX10.9.sdk.tar.xz;
                sudo tar xfz MacOSX10.9.sdk.tar.xz -C /opt/;
          - name: Do Build
            shell: bash -l {0}
            run: |
                conda install boa --yes
                conda mambabuild apfel --use-local

          - name: Upload
            shell: bash -l {0}
            run: |
                if [ "$RUNNER_OS" = "Linux" ]; then
                    OSFOLDER=linux-64
                elif [ "$RUNNER_OS" = "macOS" ]; then
                    OSFOLDER=osx-64
                else
                    exit 41
                fi
                scp ${CONDA_PREFIX}/conda-bld/${OSFOLDER}/*.tar.bz2 dummy@packages.nnpdf.science:~/packages/conda/${OSFOLDER}

